on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: "IMPORTANT: Entire response must be in the language with ISO code: ja-JP"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "IMPORTANT: Entire response must be in the language with ISO code: ja-JP"
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: "IMPORTANT: Entire response must be in the language with ISO code: ja-JP"
          CONFIG.MODEL: gpt-4-turbo-preview
